spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/blogapp
    username: postgres
    password: Mogusu@123
    driverClassName: org.postgresql.Driver
server:
  port: 9999



